# python examples/prop/circ_ap_fraunhofer.py
defaults:
  - defaults
  - _self_

sim:
  L: 7.5e-3  # total size of grid
  dz: 20  # distance [m]
  diam: 1e-3  # diameter of aperture [m]

shifted_fresnel:
  output_scaling: 15
  relative_shift: 0.25

plot:
  cross_section_log: True
  
