# python examples/slm/plot.py
hydra:
  job:
    chdir: True    # change to output folder


slm: "holoeye_lc2012"
# slm: "adafruit"
oversampling: 2   # wrt to SLM resolution
percent: 0.1   # percent of SLM to plot

plot:
  gamma: 2.2
  dpi: 300 # resolution of plots
  font:
    family: "Times New Roman"
    weight: "normal"
    size: 20 # fontsize of plots
